[package]
name = "slotpilotd"
description = "SlotPilot local station daemon"
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
slotpilot-api.workspace = true
slotpilot-domain.workspace = true
slotpilot-ipc.workspace = true
slotpilot-storage.workspace = true
thiserror.workspace = true

[lints]
workspace = true
